# Generated by Django 4.0.6 on 2022-07-18 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('hora', models.TimeField()),
                ('data_agendamento', models.DateTimeField(auto_now_add=True)),
                ('medico', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='medico.medico')),
            ],
        ),
    ]
